language: node_js
node_js:
  - 12
  - 10
  - 8
  - 6

script:
  - npm run test:server
  - xvfb-run --auto-servernum npm run test:browser

jobs:
  include:
    - node_js: 4
      script:
        - npm run test:server

services:
  - xvfb
